---
title: '基于深圳、温州两市的新冠疫情政策防控效果分析 '
author: "Happy Beatles<br>莫睿哲，田超，韩瑞昕，李明惠 "
date: "2020/6/5"
output:
  slidy_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 展示内容


<br>

- 引言
<br>

- 描述性统计
<br>

- 合成控制法
<br>

- 疫情动态传播模型
<br>


- 总结及讨论


# 引言

## 研究背景及意义
<br>

- 2019年12月，湖北省武汉市爆发了新冠肺炎疫情，并逐步扩散至全国。2020年1月20日，国家卫生健康委员会宣布将其纳入乙类传染病，并采取甲类传染病的预防、控制措施。
- 在疫情尚未引起全国警觉时，恰逢与春节返乡重合之际，武汉封城后的5天时间里，依然有1.88万湖北人士进入温州，温州一度成为孤悬鄂外的最严重地区，防控压力巨大。在不到一个月的时间里，当地政府通过采取强制隔离密切接触者、对小区进行封闭式管理等紧急公共卫生措施，有效控制了疫情。

---

<br>

- 2020年1月23日，广东省启动重大突发公共卫生事件一级响应，而深圳市收治新冠肺炎确诊病例已达到15人。面对春节期间大型聚集活动和春运潮的压力，深圳市同日也采取了加强交通卫生检疫、停止人群聚集性活动等防控措施，不到一个月的时间里实现新增病例零增长。
- 然而，当前境外疫情仍非常严重，我国输入病例的风险仍较高。因此，总结两市阶段性的疫情特征，量化评估阶段性防控措施的效果，借鉴两市优秀的防控经验，可为其他地区以及未来突发公共卫生事件的科学防控提供参考。

## 参考文献

### **在疫情传播率计算方面**

- 流行病学通常采用基本传染数$R_0$来描述疾病的传播率。综合早期使用SIR、SEIR等模型的文献，COVID-19的基本传染数所属区间约为[2.0, 7.0]。由于$R_0$依赖于许多参数；专家们多根据自身经验进行估计；且该参数不能很好地评估流行病的**动态传播模式**。
- Maier和Brockmann发现，政策实施前后疫情增长模型中指数增长率是**动态变化**的。
- Kuchars-ki等采用一个随机传播模式估计出，政策实施一周后，疫情日传播数降到了管控实施一周前的一半以下。
- 黄锷，乔方利基于自然增长率提出了一种只包含一个参数（疫情增长率）的疫情动态传播模型，该参数随着疫情的发展而动态变化，从而能够刻画疫情发展过程中动力特征的改变。

## 参考文献

### **在防控效果量化估计方面**

- 王学钦团队使用合成控制法拟合一个“虚拟”温州，发现温州在政策实施2-3天后效果明显，如果不实施政策，温州市在2月25日每十万人将增加5人确诊。
- 王刚使用疫情动态传播模型定量评估中国政府的管控措施效果，发现从2020年1月24日 ~ 2月18日, 全国施行的严格防控政策使得1692万 ~ 7605万人免于遭受新型冠状病毒的感染。
- 综上，本文将会总结温州及深圳两市的疫情特征，使用疫情动态传播模型以及合成控制法分析温州及深圳两市防控效果，并通过政策推迟的逐日累计效应对防控效果进行量化评估。

## 参考文献

- [1]Maier B F, Brockmann D. Effective containment explains sub-exponential growth in confirmed cases of recent COVID-19 outbreak in Mainland China. 2020, arXiv: 2002.07572v1.
- [2]Kucharski A J, Russell T W, et al. Early dynamics of transmission and control of COVID-19: A mathematical modelling study.
medRxiv, 2020, doi: 10.1101/2020.01.31.20019901
- [3]黄锷,乔方利.一种数据驱动的动态新型流行病传播率的提出及其在2019-nCoV疫情中的应用（英文）[J].Science Bulletin,2020,65(06): 425-427.
- [4]王刚,黄锷,乔方利.疫情管控效果的一种定量化评估方法:以COVID-19为例[J].科学通报,2020,65(11):1009-1015.

## 参考文献(续)

<br>

- [5]王学钦,史家睿,等.从病例数据对比分析影响温州与深圳疫情的特征[R],2020.03.15
- [6]刘友金,曾小明.房产税对产业转移的影响:来自重庆和上海的经验证据[J].中国工业经济,2018(11):98-116.
- [7]Alberto abadie, Alexis Diamond, and Jens Hainmueller. Synthetic Control Methods for Comparative Case Studies: Estimating the Effect of California’s Tobacco Control Program 
- [8]连玉君.合成控制法 (Synthetic Control Method) 及 Stata实现.

## 数据来源

|变量位置|变量名称|数据来源|
|---|---|---|
|描述性统计部分<br>疫情增长率部分|累计确诊人数<br>治愈人数<br>死亡人数|[深圳市政府数据开放平台][11]<br>[温州市卫生健康委员会][22]<br>[武汉市卫生健康委员会][33]<br>[国家卫生健康委员会][44]|
|合成控制法部分|累计确诊人数<br>地区生产总值<br>人口密度<br>地区常住人口|各省市卫生健康委员会<br>省级统计年鉴（2019）|
|全文|政策措施|各省、市卫健委及新闻播报|

[11]: https://opendata.sz.gov.cn/data/search/toSearch
[22]: http://wjw.wenzhou.gov.cn/
[33]: http://wjw.wuhan.gov.cn/
[44]: http://www.nhc.gov.cn/


# 2、描述性统计
# 3、合成控制法
# 4、疫情增长率
## 疫情管控效果的定量化评估方法：疫情增长率

- 疫情COVID-19的传染力较强。流行病学通常采用基本传染数$R_0$来描述疾病的传播率，但是$R_0$依赖于许多参数，这严重限制了它的实用性。
- 此外，采用一个常数来描述一个流行病发展的全过程是有些许问题的。因为在事件的不同阶段，流行病的动态可能表现出不同的传播模式。
- 而且，在各种医疗和政策的干预下，流行病的进程可能会发生动态变化。
- 因此我们选取疫情增长率这一指标建立疫情发展动力模型对政策效应进行评估。

## 1.疫情发展动力模型

建立如下疫情发展动力模型：$$N(t_{k+1})=N(t_k)*e^{a(t_{k+1})*(t_{k+1}-t_k)}, k=0,1,2,……，    （1）$$
- $t_k$:采样时间点。$a(t_k)$：随时间变化的疫情增长率。<br/>
- $N(t_k)$:与$t_k$时刻对应的现存感染者数量。<br/>
- 现存感染者数量=确诊病例数-治愈病例数-死亡病例数<br/>
疫情增长率的表达式:$$a(t_{k+1})=ln(N(t_{k+1})/N(t_k))/(t_{k+1}-t_k)), k=0,1,2,……，    （2） $$
疫情传播率定义为:$$c(t_k)=1+a(t_k), k=0,1,2,……，    （3） $$
$c(t_k)$>1，疫情蔓延，现存感染者数量持续增加。
$c(t_k)$≤1，现存感染者总量达到峰值, 即疫情拐点出现。

# 5、总结与讨论

# 总结与讨论

## 总结与讨论

- 本文研究结果表明，温州及深圳两市在新型冠状病毒肺炎防控过程中采取了**有效且及时**的防控措施，并且都取得了很好的防控效果。若政策推迟实施，现存感染人数将会远超实际。
- 截止到2020年2月24日，温州市累计确诊病例504例，累计治愈出院307例，死亡1例，新增病例实现零增长。温州的确诊人数之多建立在“早发现、早隔离、早诊断、早治疗”的防疫工作原则上，高治愈率，低死亡率。2月1日施行的疫情防控“25条”紧急措施以最大限度减少了人员流动，以最大力度控制了疫情传播，是对民众生命的负责，对城市安全的负责。

## 总结与讨论

<br>

- 作为我国最大的移民城市，人口密度高、外来人口多给深圳带来巨大的疫情防控压力。深圳市政府坚持“外防输入、内控传播”的原则，通过严守进城关，不漏一车一人；通过筑牢小区关，100%围合封闭；通过扼守厂园关，筑坚固防疫盾。截止到2020年2月24日，深圳市累计确诊病例417例，累计治愈出院249例，死亡3例，深圳紧紧咬住三大关口，全方位应对这次挑战，防控经验值得借鉴。


---
<br>

将两市的成功防控经验总结如下：

- 防止外来输入病例，并通过全面排查尽早发现可能的感染者**控制传染源**。这是疫情初期防控措施的关键。
- 通过交通停运及小区封闭式管理等严厉的防控措施加强对老百姓的引导，减少人与人之间的接触，**切断传播途径**，快速高效控制疫情。
- 通过媒体宣传引导，凝聚疫情防控的社会共识，防止人为恶意传播，确保防控工作有序进行。

希望温州及深圳两市的成功防控经验能够成为未来我国及其他国家和地区处理相似公共卫生事件的参考。

# 感谢观看
