---
title: "疫情中的数据科学项目建议书"
author: "莫睿哲 田超 李明惠 韩瑞昕"
date: "2020/4/1"
output:
  html_document: default
  pdf_document: default
geometry: lmargin=2.5cm rmargin=2.5cm
fontsize: 12pt
documentclass: article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 引言

2019年12月以来，湖北省武汉市持续开展流感及相关疾病监测，发现多起病毒性肺炎病例，均诊断为病毒性肺炎/肺部感染。2020年1月30日，世卫组织发布新型冠状病毒感染肺炎疫情为国际关注的突发公共卫生事件。3月11日，世界卫生组织总干事谭德赛宣布，新型冠状病毒已构成全球大流行。
本文根据王学钦教授的报告“从病例数据对比分析影响温州与深圳疫情的特征”,使用R里的“ggplot2”、“REmap"程序包，对不同地区的疫情数据分析其各自的特征。

## 数据来源

本文的数据来自于R程序包“nCov2019”（https://github.com/GuangchuangYu/nCov2019）。 该程序包 除了详细的实时统计信息外，还包含中国详细的城市级数据和世界范围内的国家级数据。数据将从2020年1月13日起每天自动更新。数据中的变量名包括时间（天）、国家、国家代码、省、省代码、城市、城市代码、确诊人数、疑似人数、治愈人数、死亡人数等。

部分数据如下表所示：

|  |confirm|suspect|dead|heal|nowConfirm|nowSevere|importedCase|deadRate|healRate|date |
|-:|------:|------:|---:|---:|---------:|--------:|-----------:|-------:|-------:|----:|
| 1|   41  |   0   |1   |0   |0         | 0       |0           |2.4     |0.0     |01.13|
| 2|   41  |   0   |1   |0   |0         | 0       |0           |2.4     |0.0     |01.14|
| 3|   41  |   0   |2   |5   |0         | 0       |0           |4.9     |12.2    |01.15|
| 4|   45  |   0   |2   |8   |0         | 0       |0           |4.4     |17.8    |01.16|
| 5|   62  |   0   |2   |12  |0         | 0       |0           |3.2     |19.4    |01.17|
| 6|  198  |   0   |3   |17  |0         | 0       |0           |1.5     |8.6     |01.18|

## 统计方法

预计有以下几个思路，具体实现情况以实际为准：
1、对covid-19的数据进行可视化分析，主要使用R软件中的ggplot2包以及REmap包。
2、对不同地区疫情差异是否与年龄、性别以及输入情况有关进行检验，主要使用卡方检验。
3、利用合成控制法(SMC)对某地区的政策因果效应进行估计。
4、利用快速风险评估方法对不同省市的疫情进行评估。

## 挑战及解决思路

1、REmap包生成动态图像难度较高，需从网上调研并学习前辈们的经验。
2、第一次使用合成控制法，且该方法大多使用Stata完成，在R中还需进一步学习。
