---
title: "疫情管控效果的定量化评估方法：疫情增长率"
author: "Happy Beatles"
date: "2020/6/1"
output:
  slidy_presentation: default
  html_document: default
  ioslides_presentation: default
mathjax: local
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 疫情管控效果的定量化评估方法：疫情增长率

- 疫情COVID-19的传染力较强。流行病学通常采用基本传染数$R_0$来描述疾病的传播率，但是$R_0$依赖于许多参数，这严重限制了它的实用性。
- 此外，采用一个常数来描述一个流行病发展的全过程是有些许问题的。因为在事件的不同阶段，流行病的动态可能表现出不同的传播模式。
- 而且，在各种医疗和政策的干预下，流行病的进程可能会发生动态变化。
- 因此我们选取疫情增长率这一指标建立疫情发展动力模型对政策效应进行评估。
## 1.疫情发展动力模型
建立如下疫情发展动力模型：$$N(t_{k+1})=N(t_k)*e^{a(t_{k+1})*(t_{k+1}-t_k)}, k=0,1,2,……，    （1）$$
- $t_{k+1}$、$t_k$:两个采样时间点, 通常取相邻的两天。
- $N(t_{k+1})$,$N(t_k)$:与$t_{k+1}$和$t_k$时刻对应的现存感染者数量。
- 现存感染者数量=确诊病例数-治愈病例数-死亡病例数
- a(t_k)为随时间变化的疫情增长率。
疫情增长率的表达式:$$a(t_{k+1})=ln(N(t_{k+1})/N(t_k))/(t_{k+1}-t_k)), k=0,1,2,……，    （2） $$
疫情传播率定义为:$$c(t_k)=1+a(t_k), k=0,1,2,……，    （3） $$
若$c(t_k)$>1，表示疫情蔓延，现存感染者数量持续增加。
若$c(t_k)$\leq1，表示现存感染者总量达到峰值, 即疫情拐点出现。
## 2.疫情动态传播率对比
- 由感染率对比图可知，全国的疫情拐点于2月18日出现，武汉的疫情拐点于2020年2月19日出现，深圳的疫情在2月9日达到拐点，温州的疫情在2月10日也已达到拐点。当然, 并不排除疫情的发展可能会出现一些振荡. 从动态传播率的变化趋势来看, 控制措施整体上有效地抑制了疫情的蔓延。

## 3.政策效果的评估

|  地区 |  时间段   | 初值 | 终值 | 增长率  |
| ----- |  -------  | ---- | ---- | ------- |
| 深圳  | 1/19-1/23 | 1    | 15   | 0.64    |
| 深圳  | 1/19-1/24 | 1    | 20   | 0.58    |
| 深圳  | 1/19-2/09 | 1    | 368  | 0.64    |
| 深圳  | 1/19-2/24 | 1    | 417  | 0.58    |

---

|  地区 |  时间段   | 初值 | 终值 | 增长率  |
| ----- |  -------  | ---- | ---- | ------- |
| 温州  | 1/21-1/23 | 2    | 6    | 0.55    |
| 温州  | 1/21-1/27 | 2    | 60   | 0.57    |
| 温州  | 1/21-1/28 | 2    | 114  | 0.58    |
| 温州  | 1/21-2/01 | 2    | 265  | 0.44    |
| 温州  | 1/21-2/09 | 2    | 464  | 0.28    |
| 温州  | 1/21-2/24 | 2    | 504  | 0.13    |


## 4.政策推迟的逐日累积效应
- 我们采用增长率模型来做估算，分析温州和深圳两个地区的政策推迟实施对疫情带来的影响。模型分3个时间段估算：实际管控开始之前的时段、实际管控与假定管控开始之间的时段、假定管控开始之后的时段。参考温州和深圳两市的政策，我们分别选取了以下时段：
<br/>
- 第一时段：现存感染者采用统计数据，不做任何近似处理。<br/>
- 第二时段：增长率设为常数, 用增长率计算现存感染者数量。<br/>
- 第三时段：采用从假定管控日期开始的实际增长率。<br/>

--- 

|  地区 |  第一时段  | 第二时段                 | 第三时段  |
| ----- |  -------- | ---------------------   | -------- |
| 温州  | 2月1日之前 | 2月2日（延迟1天）        |2月2日之后 |
|       | 2月1日之前 | 2月2日-2月3日（延迟2天） |2月3日之后 |
|       | 2月1日之前 | 2月3日-2月4日（延迟3天） |2月4日之后 |


|  地区 |  第一时段  | 第二时段                  | 第三时段   |
| ----- |  -------- | ---------------------    | -------   |
| 深圳  | 1月23日之前| 1月24日（延迟1天）        |1月24日之后 |
|       | 1月23日之前| 1月24日-1月25日（延迟2天）|1月25日之后 |
|       | 1月23日之前| 1月24日-1月26日（延迟3天）|1月26日之后 |

--- 

- 其中用到的典型时段的疫情增长率估计值如下表：

|  地区 |  时间段   | 初值 | 终值 | 增长率  |
| ----- |  -------  | ---- | ---- | ------- |
| 深圳  | 1/19-1/23 | 1    |  13  | 0.641237|
| 温州  | 1/21-1/31 | 2    | 232  | 0.475459|


-得出的温州和深圳的政策推迟效果如下：

-温州深圳两市从政策开始施行的时间，进行1-7天的政策延迟，由疫情传播模型得到现存感染者与实际统计数据相比的增加的感染人数。假定管控推迟1~7天开始实施, 预估现存感染者数量比实际统计数据所增加的量值。管控推迟, 对于全国或者湖北地区来说, 现存感染者数量将会随着管控推迟的时间而快速增加。 管控开始越晚, 现存感染者总数增加越快。

- 深圳市从2020年1月23日开始, 政策延迟1-7天。 若严格管控推迟1天实施,  截至2020年2月24日深圳现存感染者数量将比实际统计数据高出61人, 若政策推迟7天截至2020年2月24日深圳现存感染者数量将比实际统计数据高出1621人。

- 温州市从2月1日开始，政策延迟1-7天。若严格管控推迟1天实施, 截至2020年2月24日深圳现存感染者数量将比实际统计数据高出92人, 若政策推迟7天截至2020年2月24日深圳现存感染者数量将比实际统计数据高出3068人。



