---
title: "防疫政策效果评价"
author: "Happy Beatles"
date: "2020/6/5"
output:
  ioslides_presentation: default
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 防疫政策效果评价：以温州、深圳为例
<br/>

- 疫情显露初期，各地区积极出台防控新冠肺炎政策，如何防疫评价政策效果？

- 合成控制法是评价政策效果的一种“诚实、透明”的方法。本章以温州市和深圳市两地区为例，探究其防疫政策效果。

- 此外，基于此方法，本章继续探讨并量化了两地区政策推迟实施所造成的后果。

## 合成控制法步骤
<br/>

1、筛选合适的控制组，确定合理的预测变量；  
  
2、拟合一个适宜的反事实合成组；  
  
3、对比合成组与处理组的差异以评估政策冲击的影响； 
  
4、安慰剂检验

## 控制组和变量选择
### 控制组选择思路
<br/>

- 选定初始控制组为除自治区、特别行政区、台湾之外的268个地区，但是这些城市与温州、深圳的相似程度差别有大有小，且预测变量和结果变量数据的搜集和分析难度较大。  

- 故在实施合成控制法之前需要根据各城市的地区生产总值、人口密度、以及累计确诊病例数三个变量通过K-means聚类筛选出与政策实施地区相似度较高的城市。

---


### 聚类结果分析


- 根据SSE准则将地区分为四类，每个聚类中的个案数目结果如下：

|   类别   |数目  |
| ---------|------|
|    1     | 160  |
|    2     |  18  |
|    3     |  29  |
|    4     |  61  |
|   有效   | 268  |
|   缺失   |   0  |

---

<br/>

- 温州被聚到了第3类，这一类有29个地区。我们选取除温州外的28个地区作为合成控制法的控制组，分别是：  
沈阳、抚顺、南京、无锡、徐州、苏州、宿迁、杭州、宁波、舟山、丽水、天门、黄山、三亚、三明、南昌、上饶、济南、东营、三门峡、汕尾、宜昌、荆门、荆州、新余、汕头、商丘、揭阳。

- 深圳被聚到了第2类，这一类有18个地区。我们选取除温州外的17个地区作为合成控制法的控制组，分别是：  
北京、天津、重庆、上海、广州、合肥、蚌埠、九江、宜春、襄阳、黄冈、咸宁、信阳、岳阳、珠海、青岛、济南。

---

### 主要变量
<br/>

- 结果变量：发病率（每十万人确诊率）

- 预测变量：lnGDP

- 预测变量：ln人口密度

- 预测变量：累计确诊人数


